In [1]:
import pandas as pd
from sklearn.svm import OneClassSVM
from sklearn.preprocessing import StandardScaler

df = pd.read_csv('/Users/yuwenbo/Downloads/test/Stagged_data.csv')

In [2]:
#Drop the columns contain words and bucket.
df = df.drop(columns=['Country'])
df = df.drop(columns=['Emissions Unit'])
df = df.drop(columns=['ColdestMonth'])
df = df.drop(columns=['HottestMonth'])
df = df.drop(columns=['CO2_Emissions_Bucket'])
df = df.drop(columns=['GreenhouseGas_Emissions_Bucket'])
df = df.drop(columns=['Methane_Emissions_Bucket'])
df = df.drop(columns=['NitrousOxide_Emissions_Bucket'])
df = df.drop(columns=['FluorinatedGases_Emissions_Bucket'])
df = df.drop(columns=['Total_emissions_Bucket'])
df = df.drop(columns=['YearlyTemperatureChange_Bucket'])

In [3]:
#Select features for outlier detection
features = df.columns 


scaler = StandardScaler()
scaled_features = scaler.fit_transform(df[features])

#Detecting outliers using One-Class SVM
ocsvm = OneClassSVM(gamma='auto', nu=0.01)
ocsvm.fit(scaled_features)

#Predict the outliers, where -1 indicates an outlier and 1 indicates a normal observation
df['Outlier'] = ocsvm.predict(scaled_features)

df

,Unnamed: 0,Surrogate Keys,Year,CO2_Emissions,GreenhouseGas_Emissions,Methane_Emissions,NitrousOxide_Emissions,FluorinatedGases_Emissions,Total_emissions,AverageYearlyTemperature,ColdestMonthTemperature,HottestMonthTemperature,YearlyTemperatureChange,Outlier
0,0,1,1970,64870.726,184.520,165907.311,83831.162,17020.902,331814.621,24.322,20.988,25.910,0.000,1
1,1,2,1971,65698.450,230.533,167785.878,84608.623,17248.272,335571.756,23.933,20.897,25.542,-0.389,-1
2,2,3,1972,71123.001,256.200,176209.783,87357.595,17472.986,352419.567,24.199,20.998,26.230,0.266,1
3,3,4,1973,80463.563,292.605,189116.515,90787.751,17572.595,378233.030,24.400,20.976,26.209,0.201,1
4,4,5,1974,84212.721,328.357,193014.219,90651.557,17821.585,386028.439,23.830,20.502,25.670,-0.570,-1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265227,265227,265228,2009,2385.117,43.825,4726.988,1673.451,624.595,9453.976,21.377,15.234,24.731,-0.168,1
265228,265228,265229,2010,2738.667,43.529,5218.071,1753.777,682.098,10436.142,21.986,16.377,25.943,0.609,1
265229,265229,265230,2011,3090.699,43.807,5651.262,1806.428,710.328,11302.524,21.602,15.803,25.521,-0.384,1
265230,265230,265231,2012,3188.779,44.685,5800.089,1842.330,724.295,11600.178,21.521,16.048,24.606,-0.081,1
265231,265231,265232,2013,3240.375,45.907,5890.534,1864.132,740.120,11781.067,20.711,17.000,24.075,-0.811,1